### ISSUE TITLE
Error: Module version mismatch. Expected 48, got 51.

### ISSUE THREAD

**Issue by gucong3000** [reactnativecn/node-bsdiff#2]
18:45:47 Error: Module version mismatch. Expected 48, got 51.
18:45:47     at Error (native)
18:45:47     at Object.Module._extensions..node (module.js:597:18)
18:45:47     at Module.load (module.js:487:32)
18:45:47     at tryModuleLoad (module.js:446:12)
18:45:47     at Function.Module._load (module.js:438:3)
18:45:47     at Module.require (module.js:497:17)
18:45:47     at require (internal/module.js:20:19)
18:45:47     at Object.<anonymous> (/root/.jenkins/jobs/hybrid_dev/workspace/node_modules/node-bsdiff/index.js:7:12)
18:45:47     at Module._compile (module.js:570:32)
18:45:47     at Module._extensions..js (module.js:579:10)
18:45:47     at Object.require.extensions.(anonymous function) [as .js] (/root/.jenkins/jobs/hybrid_dev/workspace/node_modules/babel-register/lib/node.js:152:7)

**Comment by gucong3000** [comment]
Description:    Debian GNU/Linux 8.6 (jessie)
Release:        8.6

**Comment by tdzl2003** [comment]
You should run 'npm rebuild' after you upgraded node version.
